# Generated by Django 4.2.5 on 2023-11-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0005_news_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Lecture',
        ),
    ]
