# Generated by Django 4.2.5 on 2023-11-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0006_rename_news_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
        migrations.AddField(
            model_name='lecture',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на занятие'),
        ),
    ]
