# Generated by Django 4.2.5 on 2023-12-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0010_folder_parent_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
