# Generated by Django 4.2.5 on 2023-12-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0011_delete_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на архив'),
        ),
    ]
