# Generated by Django 4.2.5 on 2023-11-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_pasport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pasport',
        ),
    ]
